import 'package:ink_mobile/localization/strings/language.dart';

class RussianStrings extends LanguageStrings {
  const RussianStrings() : super();

  final String appName = "ИНК-Портал";
  final String home = "Главная";
  final String search = "Поиск";
  final String messages = "Сообщения";
  final String menu = "Меню";
  final String welcomeTxt = "Добро пожаловть в ИНК-Портал!";
  final String signIn = "Авторизация";
  final String signInInstructions = "Инструкция по входу";
  final String password = "Пароль";
  final String authHint =
      "Необходимо ввести логин и пароль от своей учетной записи в формате login (где login – Ваш логин от учётной записи во внутренней сети компании).";
  final String login = "Логин";
  final String enter = "Вход";
  final String close = "Закрыть";
  final String error = "Ошибка";
  final String announcements = "Объявления";
  final String allAnnouncements = "Все объявления";
  final String birthdays = "Дни рождения";
  final String noBirthdaysSoon = "Сегодня и ближайшие 3 дня нет дней рождения";
  final String today = "Сегодня";
  final String inComingDays = "Ближайшие дни";
  final String pageNotFound = "Страница не найдена";
  final String nowParticipatingInTheEvent = "Вы участвуете в событии";
  final String iWillParticipate = "Я пойду";
  final String events = "События";
  final String allEvents = "Все события";
  final String news = "Новости";
  final String allNews = "Все новости";
  final String newsIdea = "ИНК-Идея";
  final String volunteerNews = "Волонтерское движение";
  final String sportNews = "Спорт";
  final String msNews = "Молодежный совет";
  final String openUniversity = "Открытый университет";
  final String comments = "Комментарии";
  final String answer = "Ответить";
  final String writeCommentHint = "Написать комментарий...";
  final String commentSendingError =
      "Произошла ошибка при отправке комментария";
  final String noCommentsNewsSection = "К данной новости еще нет комментариев";
  final String oneCommentNoun = "Комментарий";
  final String multipleCommentsNoun = "Комментария";
  final String lotOfCommentsNoun = "Комментариев";
  final String aboutProject = "О проекте";
  final String inkLiteracy = "ИНК-грамотность";
  final String learningMaterials = "Обучающие материалы";
  final String phone = "Телефон";
  final String textCopied = "Текст скопирован в буфер обмена";
  final String staffMovements = "Кадровые перемещения";
  final String position = "Должность";
  final String dateOfTakingPosition = "Дата вступления в должность";
  final String department = "Подразделение";
  final String company = "Организация";
  final String status = "Статус";
  final String staffNumber = "Табельный номер";
  final String oldPosition = "Старая";
  final String newPosition = "Новая";
  final String noStaffMovements = "Кадровые перемещения отсутствуют";
  final String birthday = "День рождения";
  final String mainInformation = "Основная информация";
  final String address = "Адрес";
  final String office = "Кабинет";
  final String contacts = "Контакты";
  final String workPhone = "Рабочий телефон";
  final String workMobilePhone = "Рабочий мобильный телефон";
  final String mobilePhone = "Мобильный телефон";
  final String thank = "Поблагодарить";
  final String nothingFound = "Ничего не найдено";
  final String searchEmptyString = "Введите запрос в поисковую строку";
  final String employees = "Сотрудники";
  final String searchHint = "Найти...";
  final String services = "Сервисы";
  final String myData = "Мои данные";
  final String feedback = "Обратная связь";
  final String transportOrdering = "Заказ служебного транспорта";
  final String orderInquiry = "Заказ справок";
  final String getMedicalInsurance = "Оформление ДМС";
  final String socialPackage = "Социальный пакет";
  final String voluntaryMedicalInsurance =
      "Добровольное медицинское страхование";
  final String accidentInsurance = "Страхование от несчастных случаев";
  final String financialAid = "Материальная помощь";
  final String childrenRest = "Детский отдых";
  final String christmasGifts = "Новогодние подарки";
  final String recreationalActivities = "Оздоровительные мероприятия";
  final String noConnectionError = "Отсутствует подключение к интернету";
  final String errorOccuried = "Произошла ошибка";
  final String unknownError = "Произошла непредвиденная ошибка";
  final String reload = "Обновить";
  final String signOff = "Выйти";
  final String changeLanguage = "Сменить язык";
  final String userNotFound = "Пользователь не найден";
}
