name: ink_mobile
description: INK Group mobile application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.3.1+103010

environment:
    sdk: ">=3.1.3 <4.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ^1.0.6
    flutter_svg: ^2.0.7
    flutter_html: ^3.0.0-beta.2
    openapi:
        path: "./main_api_client"
    flutter_bloc: ^8.1.3
    path_provider: ^2.1.1
    easy_rich_text: ^2.0.0
    flutter_secure_storage: ^9.0.0
    smooth_page_indicator: ^1.1.0
    intl: ^0.18.1
    shimmer: ^3.0.0
    share_plus: ^7.2.1
    xxtea: ^2.1.0
    # flutter_contacts: ^1.1.7+1
    app_links: ^3.4.5

    ###modal_bottom_sheet: ^2.1.2
    modal_bottom_sheet: 3.0.0-pre
 #   git:
  #     url: https://github.com/followthemoney1/modal_bottom_sheet.git
   #    ref: main
    #   path: modal_bottom_sheet

    device_info_plus: ^9.0.3
    package_info_plus: ^4.1.0
    multi_select_flutter:
        path: "./custom/libs/multi_select"
    file_picker: ^5.5.0
    mask_text_input_formatter: ^2.5.0
    get_it: ^7.6.4
    injectable: ^2.3.1
    flutter_linkify: ^6.0.0
    flutter_keyboard_visibility: ^5.4.1
    flutter_local_notifications: ^15.1.2
    logging: ^1.2.0
    local_auth: ^2.1.7
    remove_emoji: ^0.0.10
    uuid: ^3.0.7
    json_annotation: ^4.8.1
    flutter_native_text_input:
        path: "./custom/libs/native_text_input"
    cached_network_image: ^3.3.0
    flutter_emoji: ^2.5.1
    pinput: ^3.0.1
    retrofit: ^4.0.2
    google_fonts: ^4.0.5
    hydrated_bloc: ^9.1.2
    socket_io_client: ^1.0.2
    scrollable_positioned_list: ^0.3.8
    # logger: ^2.0.2
    # flutter_logs: ^2.1.11
    flutter_easyloading: ^3.0.5
    equatable: ^2.0.5
    # drift: ^2.11.1
    chewie: ^1.7.1
    flutter_jailbreak_detection: ^1.10.0
    flutter_bbcode: ^1.4.1
    flutter_html_table: ^3.0.0-beta.2
    video_player: ^2.8.1
    webview_flutter: ^4.4.2
    flutter_widget_from_html: ^0.10.5
    custom_refresh_indicator: ^2.2.1


    onesignal_flutter: ^5.0.3

    image_picker: ^1.0.4
    # flutter_contacts: ^1.1.7+1
    permission_handler: ^10.4.5
    geolocator: ^10.1.0

    pull_to_refresh: ^2.0.0
    firebase_core: ^2.17.0
    url_launcher: ^6.1.14
    appmetrica_plugin: ^1.4.0
    badges: ^3.1.2
    dio: ^5.3.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    # mocktail: ^1.0.0
    injectable_generator: ^2.4.0
    # drift_dev: ^2.11.1
    # yaml:
    # flutter_native_splash: ^2.2.4
    flutter_lints: ^2.0.0
    retrofit_generator: ^8.0.0
    json_serializable: ^6.7.1
    build_runner: ^2.4.6
    flutter_launcher_icons: ^0.11.0
    analyzer: ^5.13.0

flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/app_logo_with_background.png"

flutter_native_splash:
    color: "#1d3a2e"
    image: "assets/images/splash_screen_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    generate: true
    uses-material-design: true
    assets:
        - assets/images/
        - assets/images/avatars/
        - assets/svg/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: Helvetica
          fonts:
              - asset: fonts/Helvetica.otf
        - family: Ink_icons
          fonts:
              - asset: fonts/Ink_icons.ttf
        - family: Noto
          fonts:
              - asset: fonts/noto/NotoSans-Regular.ttf
        - family: OpenSansEmoji
          fonts:
              - asset: fonts/OpenSansEmoji/OpenSansEmoji.ttf

    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
