name: ink_mobile
description: INK Group mobile application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.81+93

environment:
    sdk: ">=2.14.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
    cupertino_icons: ">=1.0.2 <2.0.0"
    flutter_svg: ^1.0.3
    flutter_html: ^3.0.0-alpha.2
    intro_slider: ">=2.4.3 <3.0.0"
    main_api_client:
        path: "./main_api_client"
    flutter_bloc:
    path_provider:
    easy_rich_text:
    flutter_secure_storage:
    smooth_page_indicator:
    intl: ">=0.17.0 <1.0.0"
    flick_video_player: ">=0.3.1"
    flutter_launcher_icons: ">=0.8.0 <1.0.0"
    shimmer: ">=2.0.0 <3.0.0"
    modal_bottom_sheet: ^2.0.0
    device_info_plus:
    package_info_plus:
    multi_select_flutter:
        path: "./custom/libs/multi_select"
    file_picker: ^4.1.1
    mask_text_input_formatter: ^2.1.0
    get_it: ^7.2.0
    messagepack: ^0.2.1
    # dart_nats_streaming:
    #     git: https://github.com/JetRabbits/dart-nats-streaming.git
    dart_nats_streaming:
        path: "./custom/libs/dart-nats-streaming-master"
    injectable:
    flutter_linkify: ^5.0.2
    flutter_keyboard_visibility: ^5.2.0
    image_picker: ^0.8.4+10
    moor: ^4.6.1+1
    transparent_image: ^2.0.0
    encrypted_moor:
        git:
            url: https://github.com/simolus3/moor.git
            path: extras/encryption
    flutter_local_notifications: ^9.3.3
    archive:
    share_plus:
    logging:
    local_auth: ^1.1.11
    remove_emoji: ^0.0.6
    safe_device:
    keyboard_dismisser: ^2.0.1
    easy_debounce: ^2.0.2+1
    firebase_messaging: ^11.2.5
    uuid: ^3.0.6
    json_annotation: ^4.4.0
    substring_highlight:
        path: "./custom/libs/substring_highlight-master"
    flutter_native_text_input: ^2.1.1
    cached_network_image: ^3.2.0
    emoji_picker_flutter: ^1.1.2
    flutter_emoji: ^2.4.0
    pinput: ^2.2.5
    retrofit: ^3.0.1+1

dev_dependencies:
    flutter_test:
        sdk: flutter
    mocktail: ^0.1.4
    build_runner: ^2.1.7
    injectable_generator:
    moor_generator: ^4.6.0+1
    yaml:
    flutter_native_splash: ^1.3.3
    json_serializable: ^6.0.0
    retrofit_generator: ^3.0.1+1

flutter_icons:
    android: true
    ios: true
    image_path: "assets/images/app_logo_with_background.png"

flutter_native_splash:
    color: "#1d3a2e"
    image: "assets/images/splash_screen_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    generate: true
    uses-material-design: true
    assets:
        - assets/certs/
        - assets/images/
        - assets/images/avatars/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: Helvetica
          fonts:
              - asset: fonts/Helvetica.otf
        - family: Ink_icons
          fonts:
              - asset: fonts/Ink_icons.ttf
        - family: Noto
          fonts:
              - asset: fonts/noto/NotoSans-Regular.ttf
        - family: OpenSansEmoji
          fonts:
              - asset: fonts/OpenSansEmoji/OpenSansEmoji.ttf

    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
