// Mocks generated by Mockito 5.0.16 from annotations
// in ink_mobile/test/messenger/svt.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;
import 'dart:typed_data' as _i3;

import 'package:ink_mobile/constants/messenger.dart' as _i2;
import 'package:ink_mobile/providers/lock_app.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [CertificateReader].
///
/// See the documentation for Mockito's code generation for more information.
class MockCertificateReader extends _i1.Mock implements _i2.CertificateReader {
  MockCertificateReader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get path =>
      (super.noSuchMethod(Invocation.getter(#path), returnValue: '') as String);
  @override
  _i3.Uint8List get data => (super.noSuchMethod(Invocation.getter(#data),
      returnValue: _i3.Uint8List(0)) as _i3.Uint8List);
  @override
  _i4.Future<void> read() => (super.noSuchMethod(Invocation.method(#read, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [LockApp].
///
/// See the documentation for Mockito's code generation for more information.
class MockLockApp extends _i1.Mock implements _i5.LockApp {
  MockLockApp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> canCheckBiometrics() =>
      (super.noSuchMethod(Invocation.method(#canCheckBiometrics, []),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  _i4.Future<void> init() => (super.noSuchMethod(Invocation.method(#init, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<bool> authentificate() =>
      (super.noSuchMethod(Invocation.method(#authentificate, []),
          returnValue: Future<bool>.value(false)) as _i4.Future<bool>);
  @override
  String toString() => super.toString();
}
