name: main_api_client
version: 0.1.0
description: Project Main API
environment:
    sdk: ">=2.12.0 <3.0.0"
dependencies:
    dio: ^4.0.0
    built_value: ^8.0.5
    built_collection: ^5.0.0
dependency_overrides:
    build_runner: ^2.4.6
    build_config: ^1.0.0
dev_dependencies:
    built_value_generator: ^8.0.5
    build_runner: ^2.4.6
    test: ^1.17.0

